release 1.0-1ppa2. remove verbose trace from postinst.

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,19 +1,47 @@
 #!/bin/sh
+# postrm script for tmp
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-	purge)
-		rm -rf /var/cache/arib25-gst-installer/*
-		;;
-	remove)
-		if [ -f /var/cache/arib25-gst-installer/installed-files ] ; then
-			rm -rf `cat /var/cache/arib25-gst-installer/installed-files`
-		fi
-		;;
+    purge)
+        rm -rf /var/cache/arib25-gst-installer/*
+        ;;
+
+    remove)
+        if [ -f /var/cache/arib25-gst-installer/installed-files ] ; then
+            rm -rf `cat /var/cache/arib25-gst-installer/installed-files`
+        fi
+        ;;
+
+    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
 exit 0
-
